# tester config file. should be overwritten by ansible in prod/stage.

DEBUG = True
DB_CONNSTR = "this gets overwritten by the tester code. it acutally uses a temp postgress db on the local disc"
REDIS_ENDPOINT = 'localhost'
REDIS_PORT = 6379

STELLAR_TIMEOUT_SEC = 10 
STELLAR_INITIAL_ACCOUNT_BALANCE = 2

ESHU_USERNAME = ''
ESHU_PASSWORD = ''
ESHU_HEARTBEAT = ''
ESHU_APPID = ''
ESHU_VIRTUAL_HOST = ''
ESHU_EXCHANGE = ''
ESHU_QUEUE = ''
ESHU_RABBIT_ADDRESS = ''

STELLAR_BASE_SEED = 'SAUBT5SXP65YYHXL3ZDR643YNCW3QURRX5Y3NAD34YNYUUMODNWTLEHU'
STELLAR_HORIZON_URL = 'https://horizon-testnet.stellar.org/'
STELLAR_NETWORK = 'TESTNET'
STELLAR_CHANNEL_SEEDS = ['SBYKNGEIHDVT7LGRUARHUVFIJNSQYVYZV7BBEO5HV6XO34ZM7L7746LW']