- hosts: all
  remote_user: "{{ remote_user | default('ubuntu') }}"
  become: true
  roles:

    #- zaxos.docker-ce-ansible-role
    - payment-service
    #- Datadog.datadog
    #- igor_mukhin.bash_aliases


  vars:
    payment_service_branch_name: lior/ECO-1091_kin_federation_support
    redis_endpoint: 'kin-app-server-stage.qugi0x.0001.use1.cache.amazonaws.com'
    datadog_api_key: "{{ lookup('aws_ssm', '/config/stage/datadog/apikey' )}}"
    datadog_config:
      tags: "service:kin-app-payment-service-stage"
    env: STAGE
    log_level: debug
    bash_aliases:
      - { alias: '_env', command: 'echo "eshu stage"' }
      - { alias: '_grep', command: 'cat /var/log/supervisor/*|grep '}
      - { alias: '_log', command: 'cat /var/log/supervisor/*' }
      - { alias: '_tail', command: 'tail -f /var/log/supervisor/* -n 10' }

  vars_files:
    - vars/kin-app-payment-service-stage.yml


