- hosts: "{{ play_hosts | first }}"
  remote_user: "{{ remote_user | default('ubuntu') }}"
  become: true
  roles:
    - kin-app-server-cron


- hosts: all
  remote_user: "{{ remote_user | default('ubuntu') }}"
  become: true
  roles:
    - weareinteractive.environment
    - Datadog.datadog
    - kin-app-server
    - igor_mukhin.bash_aliases

  vars:
   kin_app_server_branch_name: master
   deployment_env: stage
   environment_config:
     ENV: stage
     STELLAR_ACCOUNT_SID: "{{ play_hosts.index(inventory_hostname) }}" # sets the host's index within the play
   datadog_config:
     log_level: INFO
     tags: "service:kin-app-server-stage"
   datadog_api_key: "{{ lookup('aws_ssm', '/config/stage/datadog/apikey' )}}"
   debug: True
   nginx_domain: stage.kinitapp.com
   db_connstr: "postgresql://{{lookup('aws_ssm', '/config/stage/sql/userpassword')}}@kinappstage.cudbl0spntq9.us-east-1.rds.amazonaws.com/kinappstage"
   redis_endpoint: 'kin-app-server-stage.qugi0x.0001.use1.cache.amazonaws.com'
   redis_port: 6379
   eshu_username: admin
   eshu_password: admin
   eshu_exchange: eshu-exchange
   eshu_queue: eshu-queue
   eshu_virtual_host: kinapp
   eshu_appid: kinapp
   eshu_rabbit_address: 10.0.1.20
   stellar_timeout_sec: 30
   stellar_initial_account_balance: 2
   stellar_network: 'Kin Playground Network ; June 2018'
   stellar_kin_issuer_address: GBC3SG6NGTSZ2OMH3FFGB7UVRQWILW367U4GSOOF4TFSZONV42UJXUH7
   stellar_horizon_url: https://horizon-playground.kininfrastructure.com
   max_simultaneous_orders_per_user: 2
   kms_key_aws_region: 'us-east-1'
   phone_verification_enabled: True
   phone_verification_required: False
   p2p_transfers_enabled: False
   p2p_min_tasks: 0
   p2p_min_kin_amount: 0
   p2p_max_kin_amount: 200
   auth_token_send_interval_days: 1
   auth_token_enforced: False
   auth_token_enabled: True
   blackhawk_purchases_enabled: False
   blackhawk_critical_balance_threshold: 50
   payment_service_url: 'http://stage.payments.kinitapp.com:4999'
   api_server_url: 'https://stage.kinitapp.com'
   use_payment_service_phone_number_prefix: '+'
   use_payment_service_percent_of_users: 100
   block_onboarding_android_version: 1.2.5
   block_onboarding_ios_version: 1.0.0
   blocked_phone_prefixes: "['+55']"
   allowed_phone_prefixes: "['+1','+44','+972']"
   blocked_country_codes: "[]"
   truex_blacklisted_taskids: "[]"
   max_num_registrations_per_number: 9999

   bash_aliases:
     - { alias: '_env', command: 'echo "kinappserver"' }
     - { alias: '_grep', command: 'cat /var/log/kinappserver.err.log|grep '}
     - { alias: '_grepworker-fast', command: 'cat /var/log/kinappworker_fast.err.log|grep '}
     - { alias: '_grepworker-slow', command: 'cat /var/log/kinappworker_slow.err.log|grep '}
     - { alias: '_log', command: 'cat /var/log/kinappserver.err.log' }
     - { alias: '_tail', command: 'tail -f /var/log/kinappserver.err.log -n 10' }
     - { alias: '_tailworker-fast', command: 'tail -f /var/log/kinappworker_fast.err.log -n 10' }
     - { alias: '_tailworker-slow', command: 'tail -f /var/log/kinappworker_slow.err.log -n 10' }
     - { alias: '_sql', command: "psql postgresql://{{lookup('aws_ssm', '/config/stage/sql/userpassword')}}@kinappstage.cudbl0spntq9.us-east-1.rds.amazonaws.com/kinappstage" }

# add aliases to non-sudo user
- hosts: all
  remote_user: "{{ remote_user | default('ubuntu') }}"
  become: false
  roles:
    - igor_mukhin.bash_aliases

  vars:
   bash_aliases:
     - { alias: '_env', command: 'echo "kinappserver-stage"' }
     - { alias: '_grep', command: 'cat /var/log/kinappserver.err.log|grep '}
     - { alias: '_grepworker-fast', command: 'cat /var/log/kinappworker_fast.err.log|grep '}
     - { alias: '_grepworker-slow', command: 'cat /var/log/kinappworker_slow.err.log|grep '}
     - { alias: '_log', command: 'cat /var/log/kinappserver.err.log' }
     - { alias: '_tail', command: 'tail -f /var/log/kinappserver.err.log -n 10' }
     - { alias: '_tailworker-fast', command: 'tail -f /var/log/kinappworker_fast.err.log -n 10' }
     - { alias: '_tailworker-slow', command: 'tail -f /var/log/kinappworker_slow.err.log -n 10' }
     - { alias: '_sql', command: "psql postgresql://{{lookup('aws_ssm', '/config/stage/sql/userpassword')}}@kinappstage.cudbl0spntq9.us-east-1.rds.amazonaws.com/kinappstage" }

   zendesk_api_token: "{{lookup('aws_ssm', '/config/stage/zendesk/apikey')}}"